#include<iostream>
using namespace std;
main()
{
int childtickets,adulttickets,priceofchildtickets,priceofadulttickets,percentagetocharity;
string moviename;
cout<<"enter the name of movie ";
cin>>moviename;
cout<<"enter the number of adult tickets sold ";
cin>>adulttickets;
cout<<"enter the number of child tickets sold ";
cin>>childtickets;
cout<<"enter the price of adult tickets  ";
cin>>priceofadulttickets;
cout<<"enter the price of child tickets ";
cin>>priceofchildtickets;
cout<<"enter the percentage to charity ";
cin>>percentagetocharity;
int totalsale=childtickets*priceofchildtickets+adulttickets*priceofadulttickets;
cout<<"name of movie is "<< moviename<<endl;
cout<<"total amount generated by tickets is "<< totalsale<<endl;
int charity=7000;
cout<<"donation to charity "<< charity<<endl;
int remainingamout=totalsale-charity;
cout<<"remaining amount after donation "<<  remainingamout;
}